services:
  backend:
    container_name: kittygram-backend
    image: iezek1il/kittygram_backend:latest
    ports:
      - 8000:8000
    env_file:
      - .env

    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_PORT: ${POSTGRES_PORT}

    volumes:
      - backend_media:/app/media
      - static_volume:/app/static

    depends_on:
      - postgresql

  frontend:
    container_name: kittygram-frontend
    image: iezek1il/kittygram_frontend:latest
    volumes:
      - static_volume:/app/build

  nginx:
    container_name: kittygram-gateway
    image: iezek1il/kittygram_gateway:latest
    ports:
      - 80:80
    volumes:
      - backend_media:/app/media
      - static_volume:/app/build

    depends_on:
      - backend
      - frontend

  postgresql:
    image: postgres:17
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  backend_media:
  static_volume:
  postgres_data:
