name: Kittygram-app

on:
  push:
    branches:
      - main

jobs:
  backend_PEP8_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt

      - name: Test with flake8
        run: |
          python -m flake8 backend/ | true
          cd backend
          python manage.py test | true

  frontend_backend_tests:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/

  build_push_images:
    runs-on: ubuntu-latest
    needs: backend_PEP8_check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Backend build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: backend/
          push: true
          tags: iezek1il/kittygram_backend:latest
          no-cache: true

      - name: Frontend build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: frontend/
          push: true
          tags: iezek1il/kittygram_frontend:latest

      - name: Gateway build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: nginx/
          push: true
          tags: iezek1il/kittygram_gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_images

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.production.yml"
          target: "/kittygram/"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /kittygram/ 
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker compose -f docker-compose.production.yml down || true
            docker compose -f docker-compose.production.yml pull  
            docker compose -f docker-compose.production.yml up -d
            docker compose -f docker-compose.production.yml exec -T backend python manage.py migrate --noinput
            docker compose -f docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput

  telegram_notification:
    runs-on: ubuntu-latest
    needs: frontend_backend_tests

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ────────────────
            Деплой выполнен
            ────────────────

            Автор: ${{ github.actor }}
            Ветка: `${{ github.ref_name }}`
            Репозиторий: ${{ github.repository }}
            Коммит: ${{ github.event.commits[0].message }}

            ────────────────
            Успешно
            ────────────────
