name: Kittygram-app

on:
  push:
    branches:
      - main

jobs:
  backend_PEP8_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt

      - name: Test with flake8
        run: |
          python -m flake8 backend/ | true
          cd backend
          python manage.py test | true

  frontend_backend_tests:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/

  build_push_images:
    runs-on: ubuntu-latest
    needs: [backend_PEP8_check, frontend_backend_tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Backend build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: iezekiil/kittygram-backend:latest

      - name: Frontend build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: iezekiil/kittygram-frontend:latest

      - name: Gateway build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: iezekiil/build-push-action@v4

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_images

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker compose pull
            docker compose up

  # Далее Job по выполнению миграций, переносу volume и статики

  telegram_notification:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ────────────────
            Деплой выполнен
            ────────────────

            Автор: ${{ github.actor }}
            Ветка: `${{ github.ref_name }}`
            Репозиторий: ${{ github.repository }}
            Коммит: ${{ github.event.commits[0].message }}

            ────────────────
            Успешно
            ────────────────
