name: Kittygram-app

on:
  push:
    branches:
      - main

jobs:
  backend_PEP8_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt

      - name: Test with flake8
        run: |
          python -m flake8 backend/
          cd backend
          python manage.py test

  frontend_backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/

  build_push_images:
    runs-on: ubuntu-latest
    needs: [backend_PEP8_check, frontend_backend_tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Backend build and push
        run: |
          cd backend/
          docker build -t kittygram-backend . --network=host
          # Запушить образ, написать креды токена и логина

      - name: Frontend build and psuh
        run: |
          cd frontend/
          docker build -t kittygram-frontend . --natwork=host
          # Запушить образ, написать креды токена и логина

      - name: Gateway build and push
        run: |
          cd nginx/
          docker build -t kittygram-gateway . --network=host
          # Запушить образ, написать креды токена и логина

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_images

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker compose pull
            docker compose up

  # Далее Job по выполнению миграций, переносу volume и статики

  telegram_notification:
    runs-on: ubuntu-latest
    # needs: предыдущая job'a

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          # Добавить креды на телеграм
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ────────────────
            Деплой выполнен
            ────────────────

            Автор: ${{ github.actor }}
            Ветка: `${{ github.ref_name }}`
            Репозиторий: ${{ github.repository }}
            Коммит: ${{ github.event.commits[0].message }}

            ────────────────
            Успешно
            ────────────────
